apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres # Make sure this matches the label of your PostgreSQL pod
  ports:
    - protocol: TCP
      port: 5432 # The port PostgreSQL listens on
